"""add user avatar_url

Revision ID: de24f0c50104
Revises: 002
Create Date: 2026-05-12 09:13:35.921441
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'de24f0c50104'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
